version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"

  checkout.api:
    image: ${DOCKER_REGISTRY-}checkoutapi
    build:
      context: .
      dockerfile: Services/Checkout/Checkout.API/Dockerfile

  customer.web:
    image: ${DOCKER_REGISTRY-}customerweb
    build:
      context: .
      dockerfile: Services/Customer/Customer.Web/Dockerfile

  dataparser:
    image: ${DOCKER_REGISTRY-}dataparser
    build:
      context: .
      dockerfile: Services/Parser/DataParser/Dockerfile

